- hosts: all
  tasks: 
  - name: "Installing httpd"
    package:
     name: "httpd"

  - name: "copying the content to index.html file"
    copy: 
     dest: "/var/www/html/index.html"
     content: "I LOVE BASKETBALL"

  - replace:
     path: "/etc/httpd/conf/httpd.conf"
     regexp: "AllowOverride None"
     replace: "AllowOverride AuthConfig"

  - copy:
     dest: "/var/www/html/.htaccess"
     src: ".htaccess"

  - package:
     name: "python36"

  - pip:
     name: "passlib"

  - htpasswd:
     path: "/etc/www.passwd"
     name: "ankit"
     password: "redhat"

  - service:
     name: "httpd"
     status: restarted
