- hosts: ip
  tasks:
    - name: "date command running"
      command: date
      register: x

    - name: "httpd started or not"
      service:
        name: "httpd"
        state: started
      register: y

    - name: "debugging if x fails"
      debug:
        msg: "Hi testing failed"
      when: x.rc != 0

    - name: "debugging for y"
      debug:
        var: y

    - name: "debugging if command and module installs successfully"
      debug: 
        msg: "Finally Testing done"
      when: x.rc == 0 && y.failed == false