- hosts: namenode
  vars_files: 
  - variables 

  tasks:

  - name: Uploading jdk software
    copy:
      src: "{{ jdkfile }}"
      dest: "/root/"

  - name: Uploading Hadoop file
    copy: 
      src: "{{ hadoopfile }}"
      dest: "/root/"

  - name: Installing jdk
    package:
      name: "{{ jdkinstall }}"
      state: present
      disable_gpg_check: yes
    register: jdkinstall

  - name: Installing Hadoop
    command: "rpm -ivh {{ hadoopinstall }} --force"
    when: jdk_state.rc == 0

  - name: Creating namenode directory
    file:
      path: "{{ namenode_directory }}"
      state: directory

  - name: 



- hosts: datanode
  tasks: